version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /home/lo/dev/mongoDocker/data:/data/db
    ports:
      - 27017:27017
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8080:8081
